### ISSUE TITLE
希望加入支持 carousel 组件(js)

### ISSUE THREAD

**Issue by hightman** [ddouble/bsie#5]
试下用来 bsie 在 IE6 基本上比较完美了，刚刚发现 bootstrap-ie6.css 这个文件根本没有包含 carousel 这个组件的 CSS。

但原版 bootstrap.css 里有，less-ie6/ 下也有相关的 less 文件。

但这个文件里用了很多 '>' 来定义 CSS，因此 IE6 下又有问题。刚才简单测试了一下，只要把大部分的 > 删除替换为空格，然后再加入以下几行就可以了，希望官方可以进一步修正然后加入。多谢！！

``` css
.carousel-inner .item img {
  display: block;
  line-height: 1;
  width: 100%;  // 增加部分，原css定义了 max-width 但IE6还是不支持
  height: auto; // 增加部分，因为这些文件只有 ie6 加载，所以无需要用 * 开头了
}
.carousel-caption {
    _filter:alpha(opacity=70); // caption 的半透明效果
}
```
